from selenium.webdriver.common.by import By


class OrderPageLocators:
    NAME_INPUT = (By.XPATH, "//input[@placeholder='* Имя']")
    SURNAME_INPUT = (By.XPATH, "//input[@placeholder='* Фамилия']")
    ADDRESS_INPUT = (By.XPATH, "//input[@placeholder='* Адрес: куда привезти заказ']")
    METRO_INPUT = (By.XPATH, "//input[@class='select-search__input']")
    PHONE_INPUT = (By.XPATH, "//input[@placeholder='* Телефон: на него позвонит курьер']")
    NEXT_BUTTON = (By.XPATH, "//button[text()='Далее']")
    DATE_INPUT = (By.XPATH, "//input[@placeholder='* Когда привезти самокат']")
    RENTAL_PERIOD_FIELD = (By.XPATH, "//div[@class='Dropdown-placeholder' and text()='* Срок аренды']")
    SCOOTER_COLOR_BLACK = (By.XPATH, "//input[@id='black']")
    SCOOTER_COLOR_GREY = (By.XPATH, "//input[@id='grey']")
    COMMENT_INPUT = (By.XPATH, "//input[@placeholder='Комментарий для курьера']")
    SUBMIT_BUTTON = (By.XPATH, "//button[contains(@class, 'Button_Middle__1CSJM') and contains(text(), 'Заказать')]")
    CONFIRM_YES_BUTTON = (By.XPATH, "//button[text()='Да']")
    STATUS_BUTTON = (By.XPATH, "//button[text()='Посмотреть статус']")
    SCOOTER_LOGO = (By.XPATH, "//a[contains(@class, 'Header_LogoScooter__3lsAR')]")
    YANDEX_LOGO = (By.XPATH, "//a[@class='Header_LogoYandex__3TSOI']")
    ORDER_BUTTON_TOP = (By.XPATH, "//button[text()='Заказать' and contains(@class, 'Button_Button__ra12g')]")
    ORDER_BUTTON_BOTTOM = (By.XPATH, "//button[text()='Заказать' and contains(@class, 'Button_Middle__1CSJM')]")
    METRO_STATION_1 = (By.XPATH,  "//button[@value='1']")
    METRO_STATION_2 = (By.XPATH,  "//button[@value='2']")
    METRO_STATION_3 = (By.XPATH,  "//button[@value='3']")
    RENTAL_PERIOD_1 = (By.XPATH, "//div[@class='Dropdown-menu']//div[text()='сутки']")
    RENTAL_PERIOD_2 = (By.XPATH, "//div[@class='Dropdown-menu']//div[text()='двое суток']")
    RENTAL_PERIOD_3 = (By.XPATH, "//div[@class='Dropdown-menu']//div[text()='трое суток']")
    RENTAL_PERIOD_4 = (By.XPATH, "//div[@class='Dropdown-menu']//div[text()='четверо суток']")
    RENTAL_PERIOD_5 = (By.XPATH, "//div[@class='Dropdown-menu']//div[text()='пятеро суток']")
    RENTAL_PERIOD_6 = (By.XPATH, "//div[@class='Dropdown-menu']//div[text()='шестеро суток']")
    RENTAL_PERIOD_7 = (By.XPATH, "//div[@class='Dropdown-menu']//div[text()='семеро суток']")